const SECOND_PICTURE_PRICE = 8
const START_DATE_PRICE = 2
const NETWORK_PRICE = 2
const GENDRES_PRICE = 3
const COUNTRY_PRICE = 3
const DESCRIPTION_PRICE = 12
const LEVEL_COMPLETED_COINS = 20
const USER_INITIAL_COINS = 100
const FIRST_PAGE_TOP_SERIES = 1
const LAST_PAGE_TOP_SERIES = 10

export default {
  SECOND_PICTURE_PRICE,
  START_DATE_PRICE,
  NETWORK_PRICE,
  GENDRES_PRICE,
  COUNTRY_PRICE,
  DESCRIPTION_PRICE,
  LEVEL_COMPLETED_COINS,
  USER_INITIAL_COINS,
  FIRST_PAGE_TOP_SERIES,
  LAST_PAGE_TOP_SERIES
}
